import streamlit as st

st.title("⚖️ Terms & Privacy Policy")

st.markdown("""
Welcome to *Brand n Bloom*. Your privacy and trust matter to us. This page explains our Terms of Service and Privacy Policy in simple, user-friendly language.

---

### 📌 Terms of Use

By using our website and tools, you agree to:

- Use our services only for lawful purposes.
- Not copy, resell, or misuse the tools or content.
- Respect the limits of free usage (up to 3 reports/tools per day).
- Not attempt to reverse-engineer or exploit our AI tools.

Violation of these terms may lead to account suspension.

---

### 🔐 Privacy Policy

We collect limited information to help serve you better.

#### ✅ What We Collect:
- Name and email address (for sending reports).
- Basic tool usage metrics (to improve performance).
- No passwords, payment data, or personal info is stored on our servers.

#### ❌ What We Never Do:
- Never sell or share your data with third parties.
- Never store sensitive information unnecessarily.
- Never use your data for advertising without consent.

---

### 📬 Communication

You may receive:
- Reports generated by our tools via email.
- Occasional updates, unless opted out.

You can unsubscribe anytime.

---

### 🧾 Payment & Refunds

- Payments (via Stripe or PayPal) are securely processed.
- Refunds are only applicable in case of technical failures, and must be requested within 7 days.

---

### 🛡️ Data Security

We use secure APIs and encrypted channels. However, you are responsible for maintaining the confidentiality of your login or email credentials.

---

### 📝 Changes

We may revise these policies over time. Continued use of Brand n Bloom implies acceptance of any updated terms.

---

For any queries, please reach out to us at:  
📧 *agency@brand-n-bloom.com*
""")
