name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Dashboard
        run: |
          docker build -f Dockerfile.dashboard -t ${{ secrets.DOCKER_USERNAME }}/dashboard:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/dashboard:latest

      - name: Build & Push API
        run: |
          docker build -f Dockerfile.api -t ${{ secrets.DOCKER_USERNAME }}/api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/api:latest
